### ISSUE TITLE
Steering angle PID?  Share .ino?

### ISSUE THREAD

**Issue by ProgramItUp** [SullyChen/Nvidia-Autopilot-TensorFlow#10]
Nice job on the Nvidia-Autopilot-TensorFlow, the code is great!  

I saw [your YouTube video ](https://www.youtube.com/watch?v=nzKzee-Mhnc)on collecting the steering angle via the ODBII port with an Arduio.  I was looking at[ ODBII PID's ](http://obdcon.sourceforge.net/2010/06/obd-ii-pids/)but have not been able to find one for steering angle.  

Which ODBII shield did you use for the data collection?  
Do you have any plans to share the .ino code?  If so, that would be great.

Thanks.

**Comment by SullyChen** [comment]
Hi! The .ino code is very car-specific, so it wouldn't help much to share it. However, here are the parts I used:

https://www.amazon.com/Arduino-Uno-R3-Microcontroller-A000066/dp/B008GRTSV6/ref=sr_1_3?ie=UTF8&qid=1477182561&sr=8-3&keywords=arduino+uno

https://www.amazon.com/Seeedstudio-CAN-BUS-Shield/dp/B00T3XPH6C/ref=sr_1_2?ie=UTF8&qid=1477182508&sr=8-2&keywords=canbus+shield

https://www.amazon.com/ScanTool-143301-J1962M-Female-Interface/dp/B0091QW67O/ref=sr_1_1?ie=UTF8&qid=1477182543&sr=8-1&keywords=db9+to+obd

https://www.amazon.com/AmazonBasics-USB-2-0-Cable-Male/dp/B00NH11KIK/ref=sr_1_3?ie=UTF8&qid=1477182594&sr=8-3&keywords=usb+a+to+b+cable

**Comment by ProgramItUp** [comment]
@SullyChen Thanks for links to the hardware you used, much appreciated.

Did you use [SeedStudio's CAN BUS library](https://github.com/Seeed-Studio/CAN_BUS_Shield)?
Did you use the .readMsgBuf function to read the data?

I have not found many good examples to learn from on the web so any tips or code is much appreciated.
I'm assuming that you hooked up the reader and turned to steering wheel back and forth to get the messageID's for the steering angle, then just logged those specific messages, is that correct?

Thanks

**Comment by ProgramItUp** [comment]
Hi @SullyChen.

Thanks again for sharing your Tensorflow code.  
Any tips, links,  or advice on the Arduino side of things would be very helpful.
How did you figure out the MessageID for the steering?

Thanks.
