### ISSUE TITLE
No such file error on run_dataset

### ISSUE THREAD

**Issue by huyouare** [SullyChen/Nvidia-Autopilot-TensorFlow#3]
IOError: [Errno 2] No such file or directory: 'driving_dataset/10000.jpg'

Seems like the linked dataset is numbered up to 7148.jpg. 

Would you mind also linking where the dataset is from? Thanks!

**Comment by SullyChen** [comment]
Hi, I collected this small dataset myself using my car. It only collected 7148 samples I think haha

**Comment by huyouare** [comment]
That's pretty cool! Did you use a gyroscope for measuring the steering rate?
