### ISSUE TITLE
Source & License of the dataset?

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [SullyChen/Nvidia-Autopilot-TensorFlow#8]
Hi, 
Can you tell me where did you find the images in the dataset? 

Thanks,
Akshay

**Comment by SullyChen** [comment]
I collected it myself.

**Comment by andrewraharjo** [comment]
@SullyChen How did you sync the data between the steering and camera ? Very interesting project, Sully

**Comment by SullyChen** [comment]
Thanks! I wrote software to interface with the car and collect the data and label it at the same time.
